using PokemonGame.PokemonBattle.Entities;
using PokemonGame.PokemonBattle.Enums;
using System.Collections.Generic;

namespace PokemonGame.PokemonBattle.Data.Moves
{
	public class Dragonpulse : Move
	{
		public override string Name => "Dragon Pulse";
		public override string Description => "The target is attacked with a shock wave generated by the user's gaping mouth.";
		public override int BasePower => 85;
		public override int PowerPoints => 10;
		public override int Priority => 0;
		public override MoveCategory Category => MoveCategory.Special;
		public override PokemonType Type => PokemonType.Dragon;
		public Dragonpulse()
		{
			CurrentPowerPoints = PowerPoints;
		}
	}
}